#include "LEDprocess.h"

void LEDinit(void){
	PDR_TEMP_1	= MODE_IO_OUTPUT;
	PDR_TEMP_2	= MODE_IO_OUTPUT;
	PDR_VB_TX	= MODE_IO_OUTPUT;
	PDR_VB_RX	= MODE_IO_OUTPUT;
	PDR_EDS_TX	= MODE_IO_OUTPUT;
	PDR_EDS_RX	= MODE_IO_OUTPUT;
	PDR_ETH_ST	= MODE_IO_OUTPUT;
	PDR_IP_ST	= MODE_IO_OUTPUT;
	
	LED_AllON();
	R_BSP_SoftwareDelay(200, BSP_DELAY_MILLISECS);
	
	LED_AllOFF();
	R_BSP_SoftwareDelay(200, BSP_DELAY_MILLISECS);
	
	LED_StepUP();
	R_BSP_SoftwareDelay(200, BSP_DELAY_MILLISECS);
	
	LED_StepDN();
	R_BSP_SoftwareDelay(200, BSP_DELAY_MILLISECS);
}
void LED_AllON(void){
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
}
void LED_AllOFF(void){
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
}
void LED_StepUP(void){
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
}
void LED_StepDN(void){
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_ON;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_OFF;
	R_BSP_SoftwareDelay(10, BSP_DELAY_MILLISECS);
	
}
void LED_LidODD(void){
	LED_TEMP_1	= LED_OFF;
	LED_TEMP_2	= LED_ON;
	LED_VB_TX	= LED_OFF;
	LED_VB_RX	= LED_ON;
	LED_EDS_TX	= LED_OFF;
	LED_EDS_RX	= LED_ON;
	LED_ETH_ST	= LED_OFF;
	LED_IP_ST	= LED_ON;
}
void LED_LidEVN(void){
	LED_TEMP_1	= LED_ON;
	LED_TEMP_2	= LED_OFF;
	LED_VB_TX	= LED_ON;
	LED_VB_RX	= LED_OFF;
	LED_EDS_TX	= LED_ON;
	LED_EDS_RX	= LED_OFF;
	LED_ETH_ST	= LED_ON;
	LED_IP_ST	= LED_OFF;
}

