#ifndef LED_CONFIG_H
#define LED_CONFIG_H


#define		LED2			PORTE.PODR.BIT.B2
#define		LED3			PORTE.PODR.BIT.B1
#define		LED4			PORTE.PODR.BIT.B0
#define		LED5			PORT6.PODR.BIT.B4
#define		LED2_PDR		PORTE.PDR.BIT.B2
#define		LED3_PDR		PORTE.PDR.BIT.B1
#define		LED4_PDR		PORTE.PDR.BIT.B0
#define		LED5_PDR		PORT6.PDR.BIT.B4

#endif